<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>try catch 구문의 사용</title>
    <script>
        /*
         willExcept 변수와 byeBye() 메서드 존재하지 않음 -> 예외 발생.
         try 구문 안에서 예외 발생하면, 더 이상 try 구문 진행하지 않고 catch 구문 실행!!
         finally 구문은 try 구문에서 예외가 발생하든 안 하든 무조건 실행!!
         */
        try {
            willExcept.byeBye();
        } catch (exeption) {
            alert('예외발생!!');
        } finally {
            alert('예외 발생 가능 부분을 통과했습니다.');
        }
    </script>
</head>
<body>

</body>
</html>